# Unordered list style
MD004:
  style: dash

# Disable check for ordered list item prefix
MD029: false

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced

# MD013/line-length - Line length
MD013:
  line_length: 80
  tables: false
