# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
name: autofix.ci

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: write

jobs:
  autofix:
    name: Autofix dist/
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'autofix.ci[bot]'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci && npm install

      - name: Run prettier
        id: format
        run: npx prettier --write .

      - name: Build
        id: build
        run: npm run bundle

      - name: Push fixed files
        id: push
        uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
